title: Ruby Jard
description: Just another ruby debugger. Provide a better experience while debugging Ruby
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
