name: Ruby

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Install tmux
      run: sudo apt install -y tmux
    - name: Start tmux
      run: tmux start-server
    - name: Install dependencies
      run: bundle install
    - name: Checking offenses
      run: bundle exec rubocop
  test-ubuntu:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7.1]
    runs-on: ubuntu-laest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install tmux
      run: sudo apt install -y tmux
    - name: Start tmux
      run: tmux start-server
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
  test-macos:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7.1]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ maatrix.ruby }}
    - name: Install tmux
      run: brew install tmux
    - name: Start tmux
      run: tmux start-server
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
  test-byebug-9-1-0:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: "./spec/gemfiles/Gemfile-byebug-9-1-0"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Install tmux
      run: sudo apt install -y tmux
    - name: Start tmux
      run: tmux start-server
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
  test-byebug-10-0-2:
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: "./spec/gemfiles/Gemfile-byebug-10-0-2"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Install tmux
      run: sudo apt install -y tmux
    - name: Start tmux
      run: tmux start-server
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
